package com.mayank.movies;

/**
 * Created by mayank on 4/2/16.
 */
public class Movie {
    public static String name[]={"AIRLIFT","COCKTAIL","WAZIR","TAMASHA","BAJRANGI BHAIJAAN","AGNEEPATH",
            "DILWALE DULHANIA LE JAYENGE","ACTION REPLAYY","LONDON PARIS NEWYORK","RACE",
            "THODA PYAAR THODA MAGIC","KISMAT KONNECTION","KAHAANI","VICKY DONOR","STUDENT OF THE YEAR",
            "SALAAM NAMASTE","GARAM MASALA","PREM RATAN DHAN PAYO","ANGRY INDIAN GODDESSES","EK PAHELI LEELA",
            "MERE DAD KI MARUTI","KARTHIK CALLING KARTHIK","WHATS YOUR RASHEE","NAYEE PADOSAN",
            "APNA SAPNA MONEY MONEY","BHEJA FRY","WELCOME BACK","GUDDU RANGEELA","JACKPOT","IMPATIENT VIVEK",
            "ATITHI TUM KAB JAOGE","LUCK BY CHANCE","DIL BOLE HADIPPA","MEERABAI NOT OUT","KRISHNA COTTAGE",
            "KUCH NA KAHO","JHOOTH BOLE KAUWA KAATE","SANAM RE","JO JEETA WOHI SIKANDAR","JEENA MARNA TERE SANG",
            "AADMI KHILONA HAI","DIL TERA AASHIQ","IZZAT KI ROTI","CHOR AUR CHAAND","HUM AAPKE HAIN KOUN",
            "ANKHON MEIN TUM HO","EK PHOOL TEEN KANTE","DHAI AKSHAR PREM KE","KAALI TOPI LAAL RUMAAL","GAYAB",
            "MADRAS CAFE","HIJACK","WOODSTOCK VILLA","KAISAY KAHEIN","JAANE BHI DO YAARO","ZINDAGGI ROCKS",
            "QAIDI","CRAZY CUKKAD FAMILY","KAAGAZ KE FOOLS","KAUN KITNE PAANI MEIN","SATRANGEE PARACHUTE",
            "CHATUR SINGH TWO STAR","TUM MILO TOH SAHI","TERA KYA HOGA JOHNNY","KABHI ALVIDA NAA KEHNA",
            "HAZAARON KHWAISHEIN AISI","DIL MAANGE MORE","CHURA LIYA HAI TUMNE","KITNE DOOR KITNE PASS",
            "CHAL MERE BHAI"
    };
    public static Integer image_id[][]={
            {R.drawable.image1a, R.drawable.image1b, R.drawable.image1c, R.drawable.image1d},
            {R.drawable.image2a, R.drawable.image2b, R.drawable.image2c, R.drawable.image2d},
            {R.drawable.image3a, R.drawable.image3b, R.drawable.image3c, R.drawable.image3d},
            {R.drawable.image4a, R.drawable.image4b, R.drawable.image4c, R.drawable.image4d},
            {R.drawable.image5a, R.drawable.image5b, R.drawable.image5c, R.drawable.image5d},
            {R.drawable.image6a, R.drawable.image6b, R.drawable.image6c, R.drawable.image6d},
            {R.drawable.image7a, R.drawable.image7b, R.drawable.image7c, R.drawable.image7d},
            {R.drawable.image8a, R.drawable.image8b, R.drawable.image8c, R.drawable.image8d},
            {R.drawable.image9a, R.drawable.image9b, R.drawable.image9c, R.drawable.image9d},
            {R.drawable.image10a, R.drawable.image10b, R.drawable.image10c, R.drawable.image10d},
            {R.drawable.image11a, R.drawable.image11b, R.drawable.image11c, R.drawable.image11d},
            {R.drawable.image12a, R.drawable.image12b, R.drawable.image12c, R.drawable.image12d},
            {R.drawable.image13a, R.drawable.image13b, R.drawable.image13c, R.drawable.image13d},
            {R.drawable.image14a, R.drawable.image14b, R.drawable.image14c, R.drawable.image14d},
            {R.drawable.image15a, R.drawable.image15b, R.drawable.image15c, R.drawable.image15d},
            {R.drawable.image16a, R.drawable.image16b, R.drawable.image16c, R.drawable.image16d},
            {R.drawable.image17a, R.drawable.image17b, R.drawable.image17c, R.drawable.image17d},
            {R.drawable.image18a, R.drawable.image18b, R.drawable.image18c, R.drawable.image18d},
            {R.drawable.image19a, R.drawable.image19b, R.drawable.image19c, R.drawable.image19d},
            {R.drawable.image20a, R.drawable.image20b, R.drawable.image20c, R.drawable.image20d},
            {R.drawable.image21a, R.drawable.image21b, R.drawable.image21c, R.drawable.image21d},
            {R.drawable.image22a, R.drawable.image22b, R.drawable.image22c, R.drawable.image22d},
            {R.drawable.image23a, R.drawable.image23b, R.drawable.image23c, R.drawable.image23d},
            {R.drawable.image24a, R.drawable.image24b, R.drawable.image24c, R.drawable.image24d},
            {R.drawable.image25a, R.drawable.image25b, R.drawable.image25c, R.drawable.image25d},
            {R.drawable.image26a, R.drawable.image26b, R.drawable.image26c, R.drawable.image26d},
            {R.drawable.image27a, R.drawable.image27b, R.drawable.image27c, R.drawable.image27d},
            {R.drawable.image28a, R.drawable.image28b, R.drawable.image28c, R.drawable.image28d},
            {R.drawable.image29a, R.drawable.image29b, R.drawable.image29c, R.drawable.image29d},
            {R.drawable.image30a, R.drawable.image30b, R.drawable.image30c, R.drawable.image30d},
            {R.drawable.image31a, R.drawable.image31b, R.drawable.image31c, R.drawable.image31d},
            {R.drawable.image32a, R.drawable.image32b, R.drawable.image32c, R.drawable.image32d},
            {R.drawable.image33a, R.drawable.image33b, R.drawable.image33c, R.drawable.image33d},
            {R.drawable.image34a, R.drawable.image34b, R.drawable.image34c, R.drawable.image34d},
            {R.drawable.image35a, R.drawable.image35b, R.drawable.image35c, R.drawable.image35d},
            {R.drawable.image36a, R.drawable.image36b, R.drawable.image36c, R.drawable.image36d},
            {R.drawable.image37a, R.drawable.image37b, R.drawable.image37c, R.drawable.image37d},
            {R.drawable.image38a, R.drawable.image38b, R.drawable.image38c, R.drawable.image38d},
            {R.drawable.image39a, R.drawable.image39b, R.drawable.image39c, R.drawable.image39d},
            {R.drawable.image40a, R.drawable.image40b, R.drawable.image40c, R.drawable.image40d},
            {R.drawable.image41a, R.drawable.image41b, R.drawable.image41c, R.drawable.image41d},
            {R.drawable.image42a, R.drawable.image42b, R.drawable.image42c, R.drawable.image42d},
            {R.drawable.image43a, R.drawable.image43b, R.drawable.image43c, R.drawable.image43d},
            {R.drawable.image44a, R.drawable.image44b, R.drawable.image44c, R.drawable.image44d},
            {R.drawable.image45a, R.drawable.image45b, R.drawable.image45c, R.drawable.image45d},
            {R.drawable.image46a, R.drawable.image46b, R.drawable.image46c, R.drawable.image46d},
            {R.drawable.image47a, R.drawable.image47b, R.drawable.image47c, R.drawable.image47d},
            {R.drawable.image48a, R.drawable.image48b, R.drawable.image48c, R.drawable.image48d},
            {R.drawable.image49a, R.drawable.image49b, R.drawable.image49c, R.drawable.image49d},
            {R.drawable.image50a, R.drawable.image50b, R.drawable.image50c, R.drawable.image50d},
            {R.drawable.image51a, R.drawable.image51b, R.drawable.image51c, R.drawable.image51d},
            {R.drawable.image52a, R.drawable.image52b, R.drawable.image52c, R.drawable.image52d},
            {R.drawable.image53a, R.drawable.image53b, R.drawable.image53c, R.drawable.image53d},
            {R.drawable.image54a, R.drawable.image54b, R.drawable.image54c, R.drawable.image54d},
            {R.drawable.image55a, R.drawable.image55b, R.drawable.image55c, R.drawable.image55d},
            {R.drawable.image56a, R.drawable.image56b, R.drawable.image56c, R.drawable.image56d},
            {R.drawable.image57a, R.drawable.image57b, R.drawable.image57c, R.drawable.image57d},
            {R.drawable.image58a, R.drawable.image58b, R.drawable.image58c, R.drawable.image58d},
            {R.drawable.image59a, R.drawable.image59b, R.drawable.image59c, R.drawable.image59d},
            {R.drawable.image60a, R.drawable.image60b, R.drawable.image60c, R.drawable.image60d},
            {R.drawable.image61a, R.drawable.image61b, R.drawable.image61c, R.drawable.image61d},
            {R.drawable.image62a, R.drawable.image62b, R.drawable.image62c, R.drawable.image62d},
            {R.drawable.image63a, R.drawable.image63b, R.drawable.image63c, R.drawable.image63d},
            {R.drawable.image64a, R.drawable.image64b, R.drawable.image64c, R.drawable.image64d},
            {R.drawable.image65a, R.drawable.image65b, R.drawable.image65c, R.drawable.image65d},
            {R.drawable.image66a, R.drawable.image66b, R.drawable.image66c, R.drawable.image66d},
            {R.drawable.image67a, R.drawable.image67b, R.drawable.image67c, R.drawable.image67d},
            {R.drawable.image68a, R.drawable.image68b, R.drawable.image68c, R.drawable.image68d},
            {R.drawable.image69a, R.drawable.image69b, R.drawable.image69c, R.drawable.image69d},
            {R.drawable.image70a, R.drawable.image70b, R.drawable.image70c, R.drawable.image70d}
    };

}
